# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='city')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(max_length=200, verbose_name='cityDesc')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='org')),
                ('clicks', models.IntegerField(default=0, verbose_name='click')),
                ('desc', models.TextField(verbose_name='orgDesc')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favNum')),
                ('image', models.ImageField(max_length=120, upload_to='org/%Y/%m', verbose_name='pic')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='city')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='teacherName')),
                ('work_years', models.IntegerField(default=0, verbose_name='workYears')),
                ('work_company', models.CharField(max_length=50, verbose_name='company')),
                ('work_pos', models.CharField(max_length=50, verbose_name='pos')),
                ('points', models.CharField(max_length=150, verbose_name='character')),
                ('clicks', models.IntegerField(default=0, verbose_name='click')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favNum')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='org')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teacher',
            },
        ),
    ]
