# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('org', 'org'), ('person', 'person'), ('school', 'school')], default='org', max_length=20, verbose_name='OrgCategory'),
        ),
    ]
